version: '3'
services:
  web:
    container_name: "graimer-web"
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always
    working_dir: /code
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    container_name: "graimer-db"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "graimer"
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306