databases:
  - name: graimer
    databaseName: graimer
    user: graimer

services:
  - type: web
    name: graimer
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn graimer.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: graimer
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4