# Generated by Django 3.2.15 on 2022-10-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='icon',
        ),
    ]
